admin_password: admin
barcode_login_enabled: true
book_check_enabled: true
library:
  attachment_acceptance_enabled: true
  checkin_enabled: true
  current_location: LB
  host: 140.125.246.11
  institution_id: HyLib
  login_enabled: false
  login_pass: ''
  login_user: ''
  mock_enabled: false
  port: 6001
logs:
  backup_days: 300
machine:
  baudrate: 9600
  port: /dev/uno
max_return_limit: 20
require_admin_login: false
