admin_password: admin
barcode_login_enabled: true
book_check_enabled: true
library:
  host: 192.168.1.100
  institution_id: MAIN
  login_enabled: false
  login_pass: ''
  login_user: ''
  mock_enabled: true
  port: 6001
logs:
  backup_days: 30
machine:
  baudrate: 38400
  port: /dev/uno
max_return_limit: 20
require_admin_login: false
